#un ambiente provee las variables globales predefinidas
#los ambientes disponibles son los siguientes
env:
  #browser global variables
  browser: false
  #commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:jest/recommended
plugins:
  - jest
parserOptions:
  ecmaVersion: 12
rules:
    # jest/no-disabled-tests: "warn"
    # jest/no-focused-test: "error"
    # jest/no-identical-title: "error"
    jest/prefer-to-have-length: "warn"
    # jest/valid-expect: "error"

