#un ambiente provee las variables globales predefinidas 
#los ambientes disponibles son los siguientes
env:
  #browser global variables
  browser: false 
  #duda sobre esta opcion, pq esta en true?
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - plugin:jest/recommended
plugins:
  - jest
parserOptions:
  ecmaVersion: 12
rules: { 

}

