version: '3'

services:
    mlmutant:
        build: .
        ports:
            - "8080:8080"
        volumes:
            - .:/opt/app
    data:
        image: mongo
        expose: 
            - "27017"
        ports:
            - "27017:27017"
        volumes:
            - ./data:/data/db
        